name: Build artifact on change
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with: 
        node-version: 14.x 

    - name: Build
      run: |
        npm install
        gulp

#     - name: 'Upload Artifact'
#       uses: actions/upload-artifact@v2
#       with:
#         name: rivendellweb-theme
#         path: theme-download/
        
    - name: "Publish Release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Development Build"
        files: |
          "theme-download/"
